<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../The25th.DataAccess/The25th.DataAccess.csproj" />
    <ProjectReference Include="../The25th.Models/The25th.Models.csproj" />
    <ProjectReference Include="../The25th.Utility/The25th.Utility.csproj" />
  </ItemGroup>

</Project>
